### PR TITLE
fixes for Wagtail 5.0

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by Aleksi44** [comment]
Thanks @PetrDlouhy 

Deployed in 0.0.10

**Comment by PetrDlouhy** [comment]
@Aleksi44 Thank you very much.
Is it possible, that you accidentally forgotten to include the new staticfiles in the bundle?
I have got following error:
```
ValueError: Missing staticfiles manifest entry for 'wagtailyoast/dist/css/styles0.0.10.css'
```

**Comment by Aleksi44** [comment]
The static files seem to be present in the bundle : https://pypi.org/project/wagtailyoast/0.0.10/#files
When I download the archive, the file `wagtailyoast/dist/css/styles0.0.10.css` is present.

Do you have this error locally or in production?

**Comment by Aleksi44** [comment]
Another subject, I really have to delete the static files of the older versions... 
I put you as a collaborator on the project if you ever want to modify/fix things don't hesitate

**Pull request merged**
